server:
  port: 8081

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:file:~/dataBase
    username: user
    password:
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2

eureka:
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/