server:
  port: 8081

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/dataBase
    username: user
    password:
    driverClassName: org.h2.Driver

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.0.134:8761/eureka/
    instance:
      leaseRenewalIntervalInSeconds: 10
      metadataMap:
        instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}

#user:
#  oauth:
#    clientId: R2dpxQ3vPrtfgF72
#    clientSecret: fDw7Mpkk5czHNuSRtmhGmAGL42CaxQB9
#    redirectUris: http://localhost:8082/login/oauth2/code/
#    username: root
#    password: root